### ISSUE TITLE
成功转13个歌词文件之后会卡住

### ISSUE THREAD

**Issue by txtyb** [MikiraSora/Netease-Lyric-Parser-For-AndroidApp#1]
试了两次，一开始正常工作，成功转了13个文件后就不能继续转了。

**Comment by MikiraSora** [comment]
在上课中下载运行，并没发现有啥问题，可能是你的网络问题，不过鉴于这货代码太渣，计划过几天就用C#/Xmarin重写一次
![image](https://user-images.githubusercontent.com/7549173/30057883-36217b3c-926b-11e7-9e2e-c42e00a18fbe.png)

**Comment by txtyb** [comment]
感谢
